### ISSUE TITLE
clean up categories

### ISSUE THREAD

**Issue by derekeder** [chihacknight/energy-news-roundup#2]
With the basic scrape completed in #1 (nice work @SuragNuthulapaty and @herrerarobert!), the next step is to review the output data and see if there's any changes to make to massage the data. I created a Google Sheet of the scraped digest items here as well as a summary table for counts of each category: https://docs.google.com/spreadsheets/d/1n_ruhDMz0g-b2yfhak1m9fq7Xr_0SY5rqPeamJqPHho/edit#gid=1843617235

From this, it looks like there are a few redundant / inconsistently named categories we're pulling like `OIL AND GAS` vs `OIL & GAS` etc: https://docs.google.com/spreadsheets/d/1n_ruhDMz0g-b2yfhak1m9fq7Xr_0SY5rqPeamJqPHho/edit#gid=934319479

We should try to clean up / merge these together. A few ideas for that:
- convert all text to uppercase and strip out all non-letter characters
- create a list of categories to ignore, like `YOUR AD HERE` and `YOUR MESSAGE HERE`
- for the `ALSO` and `MEANWHILE` articles, maybe associate them with the previously found category?

**Comment by SuragNuthulapaty** [comment]
For content to cleanup, there seems to be 186 rows that we need to manually go through, not including all the categories we should be igoring.

**Comment by derekeder** [comment]
We're at 98% accuracy on these so we call this done.
